title: Podify
tagline: Create podcasts from anything youtube-dl can handle
url: https://podify-org.github.io

show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
github:
  is_project_page: yes
  repository_name: Podify
  repository_url: https://github.com/podify-org/podify
  owner_name: Max Hollmann
  owner_url: https://github.com/maxhollmann/
  show_star_button: yes

plugins:
  - jekyll-seo-tag
