title: Podify
description: Create podcasts from anything youtube-dl can handle
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
github:
  is_project_page: yes
  repository_name: Podify
  repository_url: https://github.com/podify-org/podify
  owner_name: Max Hollmann
  owner_url: https://github.com/maxhollmann/
  show_star_button: no
